# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8      #tomcat的URI编码
        max-threads: 1000        #tomcat最大线程数，默认2000
        min-spare-threads: 30   #最小线程数
    port: 9090                    #服务端口
    servlet:
      context-path: /bootstudy   #访问路径
      session-timeout: 60

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  profiles:
    active: dev


