spring:
  redis:
    host: 127.0.0.1       #redis服务器地址
    port: 6379            #redis服务端口
    password:             #redis服务密码
    timeout: 3000          #redis超时时间（毫秒）
    database: 0           #redis数据库索引（默认为0）
    jedis:
      pool:
        max-active: 1024     #连接池最大连接数（使用负值表示无限制）
        max-wait: 1000        #连接池最大阻塞等待数（使用负值表示无限制）
        max-idle: 10          #连接池最大空闲连接
        min-idle: 0           #连接池最小空闲连接
  datasource:
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: com.mysql.jdbc.Driver
          druid:
              first:  #数据源1
                  url: jdbc:mysql://127.0.0.1:3306/gzzhyy?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                  #url: jdbc:mysql://127.0.0.1:3306/xjyddc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                  username: root
                  password: root
              initial-size: 10
              max-active: 100
              min-idle: 10
              max-wait: 60000
              pool-prepared-statements: true
              max-pool-prepared-statement-per-connection-size: 20
              time-between-eviction-runs-millis: 60000
              min-evictable-idle-time-millis: 300000
              validation-query: SELECT 1 FROM DUAL
              test-while-idle: true
              test-on-borrow: false
              test-on-return: false
              stat-view-servlet:
                  enabled: true
                  url-pattern: /druid/*
                  #login-username: admin
                  #login-password: admin
              filter:
                  stat:
                      log-slow-sql: true
                      slow-sql-millis: 1000
                      merge-sql: true
                  wall:
                      config:
                          multi-statement-allow: true







